title: premium cashew
tagline: Daily byte sized updates
description: Who knows where I take this? Starting out by posting daily thoughts and using it as a reflection board.
plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md


